/** Tree-shakeable secondary entry point for the Calendar family. */
export {
  AF_CALENDAR_SLOT_DIRECTIVES,
  AF_CALENDAR_TEMPLATE_DIRECTIVES,
  AfCalendar,
  AfCalendarComponent,
  AfCalendarDayHeaderDirective,
  AfCalendarDayTimeline,
  AfCalendarDayTimelineComponent,
  AfCalendarEmptyDirective,
  AfCalendarErrorDirective,
  AfCalendarEventDetail,
  AfCalendarEventDetailComponent,
  AfCalendarEventDirective,
  AfCalendarEventEditor,
  AfCalendarEventEditorComponent,
  AfCalendarFooterDirective,
  AfCalendarMiniMonth,
  AfCalendarMiniMonthComponent,
  AfCalendarNextSession,
  AfCalendarNextSessionComponent,
  AfCalendarStripAgenda,
  AfCalendarStripAgendaComponent,
  AfCalendarToolbarDirective,
  AfCalendarUpcoming,
  AfCalendarUpcomingComponent,
  AfCalendarWeekLoad,
  AfCalendarWeekLoadComponent,
} from '@argfit-ui/adaptive';
