/**
 * Canonical list of every CSS custom property exposed by an ArgFit UI theme.
 *
 * All tokens live in the `--af-*` namespace. Consumers should reference these
 * tokens instead of hardcoding raw values so that the design system stays
 * coherent across desktop, mobile and adaptive layers.
 */
export const AF_THEME_TOKEN_NAMES = [
  // ── Brand colour scales ─────────────────────────────────────────────
  '--af-color-primary-50',
  '--af-color-primary-100',
  '--af-color-primary-200',
  '--af-color-primary-300',
  '--af-color-primary-400',
  '--af-color-primary-500',
  '--af-color-primary-600',
  '--af-color-primary-700',
  '--af-color-primary-800',
  '--af-color-primary-900',
  '--af-color-accent-50',
  '--af-color-accent-100',
  '--af-color-accent-200',
  '--af-color-accent-300',
  '--af-color-accent-400',
  '--af-color-accent-500',
  '--af-color-accent-600',
  '--af-color-accent-700',
  '--af-color-accent-800',
  '--af-color-accent-900',
  '--af-color-neutral-50',
  '--af-color-neutral-100',
  '--af-color-neutral-200',
  '--af-color-neutral-300',
  '--af-color-neutral-400',
  '--af-color-neutral-500',
  '--af-color-neutral-600',
  '--af-color-neutral-700',
  '--af-color-neutral-800',
  '--af-color-neutral-900',

  // ── Semantic palette ────────────────────────────────────────────────
  '--af-success',
  '--af-success-light',
  '--af-success-dark',
  '--af-warning',
  '--af-warning-light',
  '--af-warning-dark',
  '--af-danger',
  '--af-danger-light',
  '--af-danger-dark',
  '--af-info',
  '--af-info-light',
  '--af-info-dark',

  // ── Primary / accent semantic aliases ───────────────────────────────
  '--af-primary',
  '--af-primary-hover',
  '--af-primary-active',
  '--af-primary-soft',
  '--af-primary-contrast',
  '--af-accent',
  '--af-accent-hover',
  '--af-accent-soft',
  '--af-secondary',
  '--af-secondary-hover',
  '--af-danger-hover',
  '--af-danger-soft',

  // ── Surfaces & backgrounds ──────────────────────────────────────────
  '--af-bg-main',
  '--af-bg-surface',
  '--af-bg-elevated',
  '--af-bg-overlay',
  '--af-bg-interactive',
  '--af-surface-1',
  '--af-surface-2',
  '--af-surface-3',
  '--af-surface-4',

  // ── Foreground / typography colour ──────────────────────────────────
  '--af-text-main',
  '--af-text-muted',
  '--af-text-soft',
  '--af-text-disabled',
  '--af-text-inverse',

  // ── Borders & focus ─────────────────────────────────────────────────
  '--af-border',
  '--af-border-soft',
  '--af-border-strong',
  '--af-border-focus',
  '--af-focus-ring',

  // ── Inputs ──────────────────────────────────────────────────────────
  '--af-input-bg',
  '--af-input-border',

  // ── Cards ───────────────────────────────────────────────────────────
  '--af-card-bg',
  '--af-card-border',
  '--af-card-shadow',

  // ── Charts ──────────────────────────────────────────────────────────
  '--af-chart-grid',
  '--af-chart-axis',
  '--af-chart-label',
  '--af-chart-primary',
  '--af-chart-accent',
  '--af-chart-success',
  '--af-chart-warning',
  '--af-chart-danger',
  '--af-chart-tooltip-bg',
  '--af-chart-tooltip-border',
  '--af-chart-tooltip-text',
  '--af-chart-track',
  '--af-chart-fill-soft',
  '--af-chart-scale-0',
  '--af-chart-scale-1',
  '--af-chart-scale-2',
  '--af-chart-scale-3',
  '--af-chart-scale-4',
  '--af-chart-scale-5',

  // ── Calendar (time grid surfaces) ───────────────────────────────────
  '--af-calendar-surface',
  '--af-calendar-surface-elevated',
  '--af-calendar-grid-line',
  '--af-calendar-today-bg',
  '--af-calendar-selection-bg',
  '--af-calendar-now',
  '--af-calendar-slot-height-compact',
  '--af-calendar-slot-height-comfortable',
  '--af-calendar-slot-height-touch',
  '--af-calendar-time-axis-width',

  // ── Calendar event colours ──────────────────────────────────────────
  '--af-event-training-accent',
  '--af-event-training-bg',
  '--af-event-training-border',
  '--af-event-match-accent',
  '--af-event-match-bg',
  '--af-event-match-border',
  '--af-event-gym-accent',
  '--af-event-gym-bg',
  '--af-event-gym-border',
  '--af-event-video-accent',
  '--af-event-video-bg',
  '--af-event-video-border',
  '--af-event-medical-accent',
  '--af-event-medical-bg',
  '--af-event-medical-border',
  '--af-event-neutral-accent',
  '--af-event-neutral-bg',
  '--af-event-neutral-border',

  // ── Scrollbar ───────────────────────────────────────────────────────
  '--af-scrollbar-thumb',

  // ── Radii ───────────────────────────────────────────────────────────
  '--af-radius-none',
  '--af-radius-xs',
  '--af-radius-sm',
  '--af-radius-md',
  '--af-radius-lg',
  '--af-radius-xl',
  '--af-radius-2xl',
  '--af-radius-pill',

  // ── Shadows / elevation ─────────────────────────────────────────────
  '--af-shadow-xs',
  '--af-shadow-sm',
  '--af-shadow-md',
  '--af-shadow-lg',
  '--af-shadow-xl',
  '--af-shadow-glow',
  '--af-shadow-glow-accent',

  // ── Spacing scale ───────────────────────────────────────────────────
  '--af-space-0',
  '--af-space-px',
  '--af-space-0_5',
  '--af-space-1',
  '--af-space-1_5',
  '--af-space-2',
  '--af-space-3',
  '--af-space-4',
  '--af-space-5',
  '--af-space-6',
  '--af-space-8',
  '--af-space-10',
  '--af-space-12',
  '--af-space-16',
  '--af-space-20',
  '--af-space-24',

  // ── Typography ──────────────────────────────────────────────────────
  '--af-font-display',
  '--af-font-body',
  '--af-font-mono',
  '--af-font-family',
  '--af-text-xs',
  '--af-text-sm',
  '--af-text-base',
  '--af-text-lg',
  '--af-text-xl',
  '--af-text-2xl',
  '--af-text-3xl',
  '--af-text-4xl',
  '--af-text-5xl',
  '--af-text-6xl',
  '--af-font-size-xs',
  '--af-font-size-sm',
  '--af-font-size-md',
  '--af-font-size-lg',
  '--af-font-size-xl',
  '--af-font-size-2xl',
  '--af-font-weight-regular',
  '--af-font-weight-medium',
  '--af-font-weight-semibold',
  '--af-font-weight-bold',
  '--af-leading-tight',
  '--af-leading-snug',
  '--af-leading-normal',
  '--af-leading-relaxed',
  '--af-line-height-tight',
  '--af-line-height-normal',
  '--af-tracking-tight',
  '--af-tracking-normal',
  '--af-tracking-wide',
  '--af-tracking-wider',
  '--af-tracking-widest',

  // ── Motion ──────────────────────────────────────────────────────────
  '--af-ease-out',
  '--af-ease-in-out',
  '--af-ease-spring',
  '--af-duration-fast',
  '--af-duration-normal',
  '--af-duration-slow',
  '--af-duration-slower',
  '--af-motion-fast',
  '--af-motion-base',
  '--af-motion-slow',
  '--af-motion-ease',

  // ── Breakpoints ─────────────────────────────────────────────────────
  '--af-breakpoint-mobile',
  '--af-breakpoint-tablet',
  '--af-breakpoint-desktop',

  // ── Button sizing ───────────────────────────────────────────────────
  '--af-button-height-sm',
  '--af-button-height-md',
  '--af-button-height-lg',
  '--af-button-padding-x-sm',
  '--af-button-padding-x-md',
  '--af-button-padding-x-lg',
  '--af-button-gap',
] as const;

export type AfThemeTokenName = (typeof AF_THEME_TOKEN_NAMES)[number];

export type AfThemeTokenMap = Readonly<Record<AfThemeTokenName, string>>;
