import type { AfThemeDefinition } from './theme.types';

export const ARGFIT_DARK_THEME: AfThemeDefinition = {
  name: 'argfit-dark',
  tokens: {
    '--af-bg-main': '#070b12',
    '--af-bg-surface': '#0d1320',
    '--af-bg-elevated': '#121b2b',
    '--af-bg-overlay': 'rgba(7, 11, 18, 0.82)',
    '--af-bg-interactive': '#162236',
    '--af-text-main': '#edf4ff',
    '--af-text-muted': '#a9b6ca',
    '--af-text-soft': '#77859a',
    '--af-text-disabled': '#536074',
    '--af-text-inverse': '#06101f',
    '--af-primary': '#38bdf8',
    '--af-primary-hover': '#67d3ff',
    '--af-primary-active': '#0ea5e9',
    '--af-primary-soft': 'rgba(56, 189, 248, 0.16)',
    '--af-primary-contrast': '#03121d',
    '--af-secondary': '#8b5cf6',
    '--af-secondary-hover': '#a78bfa',
    '--af-success': '#34d399',
    '--af-warning': '#fbbf24',
    '--af-danger': '#fb7185',
    '--af-danger-hover': '#fda4af',
    '--af-danger-soft': 'rgba(251, 113, 133, 0.16)',
    '--af-info': '#60a5fa',
    '--af-border': '#243247',
    '--af-border-soft': '#1a2638',
    '--af-border-strong': '#3a4a63',
    '--af-border-focus': '#38bdf8',
    '--af-radius-xs': '2px',
    '--af-radius-sm': '4px',
    '--af-radius-md': '6px',
    '--af-radius-lg': '8px',
    '--af-radius-xl': '12px',
    '--af-radius-pill': '999px',
    '--af-shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.28)',
    '--af-shadow-md': '0 8px 24px rgba(0, 0, 0, 0.28)',
    '--af-shadow-lg': '0 18px 48px rgba(0, 0, 0, 0.34)',
    '--af-space-1': '4px',
    '--af-space-2': '8px',
    '--af-space-3': '12px',
    '--af-space-4': '16px',
    '--af-space-5': '20px',
    '--af-space-6': '24px',
    '--af-space-8': '32px',
    '--af-space-10': '40px',
    '--af-space-12': '48px',
    '--af-font-family':
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    '--af-font-size-xs': '12px',
    '--af-font-size-sm': '14px',
    '--af-font-size-md': '16px',
    '--af-font-size-lg': '18px',
    '--af-font-size-xl': '22px',
    '--af-font-size-2xl': '28px',
    '--af-font-weight-regular': '400',
    '--af-font-weight-medium': '500',
    '--af-font-weight-semibold': '600',
    '--af-font-weight-bold': '700',
    '--af-line-height-tight': '1.15',
    '--af-line-height-normal': '1.5',
    '--af-motion-fast': '120ms',
    '--af-motion-base': '180ms',
    '--af-motion-slow': '260ms',
    '--af-motion-ease': 'cubic-bezier(0.2, 0, 0, 1)',
    '--af-breakpoint-mobile': '767.98px',
    '--af-breakpoint-tablet': '1023.98px',
    '--af-breakpoint-desktop': '1024px',
    '--af-focus-ring': '0 0 0 3px rgba(56, 189, 248, 0.32)',
    '--af-button-height-sm': '32px',
    '--af-button-height-md': '38px',
    '--af-button-height-lg': '44px',
    '--af-button-padding-x-sm': '12px',
    '--af-button-padding-x-md': '16px',
    '--af-button-padding-x-lg': '20px',
    '--af-button-gap': '8px',
  },
};
